"""Decision-time overlay logging queue — which live recs still need a decision.

Purpose: remove every gram of friction between "a rec exists" and "the operator
has logged EXECUTE / VETO / REDUCE for it". Analyses 2-4 of
``governance/AB_PREREG.md`` have n = 0 until decision-time rows exist, and lost
days are unrecoverable (the read date, 2026-09-27, does not move).

STRICTLY OUTCOME-BLIND BY CONSTRUCTION
--------------------------------------
This module must never show the operator how a rec turned out. Doing so would
contaminate the very decision being logged: the overlay's discretionary skill
is the thing under measurement, and a decision informed by hindsight measures
nothing. Two structural defences, not conventions:

1. Only rec-file columns are ever read. Settled outcomes live in
   ``data/derived/paper_leg*.parquet`` and ``trades_log.csv``; neither is
   opened here, ever.
2. :func:`assert_outcome_blind` is a hard wall — any column whose name matches
   an outcome-ish pattern raises, and the render path only emits fields on an
   explicit allowlist. Mirrors the wall in ``src/screen_52wh.py``.

WRITES NOTHING
--------------
This module never writes ``governance/overlay_log.csv``. The log records the
OPERATOR'S OWN decisions; a row generated by tooling would be indistinguishable
from a genuine one and would silently corrupt the pre-registered study. Reading
the log to work out what is already logged is the only interaction.

All rec access goes through :func:`data_gate.load_operational` (Tier 1 door).
"""

from __future__ import annotations

import re
from pathlib import Path

import pandas as pd

import data_gate

REPO = Path(__file__).resolve().parents[1]
OVERLAY_LOG = REPO / "governance" / "overlay_log.csv"
RECS_DIR = REPO / "data" / "legacy_snapshot" / "recs"
RAW_ROOT = REPO / "data" / "sealed" / "raw"

#: Source class declared to the Tier 1 door. A literal, not a derived path:
#: :func:`_rec_files` reads from RECS_DIR and RAW_ROOT and nowhere else, so
#: this names the admissible source class truthfully and stays correct when
#: the dirs are redirected in tests.
_SOURCE = "data/legacy_snapshot/recs/"

REC_KEY_RE = re.compile(r"^\d{4}-\d{2}-\d{2}\|[A-Za-z0-9&._-]+\|\d+$")

_REC_NAME = re.compile(
    r"top5_report_data(?P<data_date>\d{4}-\d{2}-\d{2})"
    r"_generated(?P<gen_date>\d{4}-\d{2}-\d{2})\.csv$"
)

#: The ONLY fields this tool will ever display. Every one is written into the
#: rec file at generation time, i.e. known before the decision is made.
DECISION_TIME_FIELDS = (
    "rec_key",
    "pick_date",
    "data_date",
    "symbol",
    "rank",
    "conviction",
    "close",
    "stop_loss",
    "target_1",
    "target_2",
)

#: Substrings that mark a column as outcome-bearing or outcome-adjacent. Any
#: match anywhere in the frame is a hard error, not a filtered-out column: its
#: presence means an outcome source was opened, which is the bug.
_OUTCOME_TOKENS = (
    "r_multiple",
    "exit",
    "pnl",
    "p_l",
    "realized",
    "realised",
    "outcome",
    "settle",
    "fill",
    "nav",
    "result",
    "return",
    "profit",
    "loss_amount",
    "mtm",
    "won",
    "win",
)


class OutcomeContactError(RuntimeError):
    """Raised when outcome-bearing data reaches the decision-time surface."""


def assert_outcome_blind(df: pd.DataFrame) -> None:
    """Hard wall: refuse frames carrying outcome or outcome-adjacent columns.

    ``stop_loss`` is explicitly permitted — it is a level in the rec, not a
    realised loss — so the token scan runs against an exemption list.
    """
    exempt = {"stop_loss", "stop_pct", "stop_method"}
    bad = []
    for col in df.columns:
        low = str(col).lower()
        if low in exempt:
            continue
        if any(tok in low for tok in _OUTCOME_TOKENS):
            bad.append(col)
    if bad:
        raise OutcomeContactError(
            f"outcome-bearing column(s) reached the decision-time surface: {bad}. "
            "This tool must be strictly forward-looking — settled results would "
            "contaminate the decision being logged (governance/AB_PREREG.md)."
        )


def _rec_files() -> list[Path]:
    """All rec CSVs from admissible sources, deduped by filename.

    Sources: ``data/legacy_snapshot/recs/`` and every ``data/sealed/raw/<day>/``
    snapshot. Both are on the Tier 1 admissible list. Raw snapshot days are
    cumulative supersets, so the union is the widest consistent corpus; seq
    assignment was verified identical across the two sources.
    """
    by_name: dict[str, Path] = {}
    for d in sorted(RAW_ROOT.iterdir()) if RAW_ROOT.is_dir() else []:
        if d.is_dir():
            for f in sorted(d.glob("top5_report_data*_generated*.csv")):
                by_name[f.name] = f
    if RECS_DIR.is_dir():
        for f in sorted(RECS_DIR.glob("top5_report_data*_generated*.csv")):
            by_name.setdefault(f.name, f)
    return [by_name[n] for n in sorted(by_name)]


def load_rec_corpus(files: list[Path] | None = None) -> pd.DataFrame:
    """Parse rec CSVs and assign rec_key = data_date|SYMBOL|seq (RULING 1).

    seq is the 1-based ordinal of the generation for that data_date, ordered by
    generated_date — identical to ``scripts/build_workspace.load_rec_files``,
    but computed over the union corpus so a key never shifts between runs.
    """
    frames = []
    for f in _rec_files() if files is None else files:
        m = _REC_NAME.search(f.name)
        if not m:
            continue
        try:
            df = pd.read_csv(f, comment="#")
        except pd.errors.EmptyDataError:
            continue  # re-generations with zero picks carry only the comment line
        if df.empty:
            continue
        df["data_date"] = m["data_date"]
        df["generated_date"] = m["gen_date"]
        frames.append(df)
    if not frames:
        return pd.DataFrame()
    recs = pd.concat(frames, ignore_index=True)
    seq = recs.groupby("data_date")["generated_date"].transform(
        lambda s: s.map({g: i + 1 for i, g in enumerate(sorted(s.unique()))})
    )
    recs["seq"] = seq.astype(int)
    recs["rec_key"] = (
        recs["data_date"] + "|" + recs["symbol"].astype(str) + "|" + recs["seq"].astype(str)
    )
    return recs


def live_window_recs(files: list[Path] | None = None) -> pd.DataFrame:
    """The decision universe: live-window recs, Tier 1 gated, outcome-blind.

    Mirrors ``scripts/run_paper_leg.load_rec_universe`` so the backlog counts
    exactly the recs the A/B will later join on: pick_date = the rec's
    GENERATED date (a rec generated on X enters X+1), and per
    (pick_date, symbol) the freshest data_date wins.
    """
    recs = load_rec_corpus(files)
    if recs.empty:
        return pd.DataFrame(columns=list(DECISION_TIME_FIELDS))
    assert_outcome_blind(recs)
    recs["pick_date"] = pd.to_datetime(recs["generated_date"])
    recs = recs.loc[recs["pick_date"] >= data_gate.LIVE_WINDOW_START]
    if recs.empty:
        return pd.DataFrame(columns=list(DECISION_TIME_FIELDS))
    recs = (
        recs.sort_values("data_date")
        .groupby(["pick_date", "symbol"], as_index=False)
        .tail(1)
    )
    keep = [c for c in DECISION_TIME_FIELDS if c in recs.columns]
    out = recs[keep].copy()
    gated = data_gate.load_operational(out, "pick_date", source=_SOURCE)
    assert_outcome_blind(gated)
    return gated.sort_values(["pick_date", "rank" if "rank" in gated else "symbol"]).reset_index(
        drop=True
    )


def logged_keys(log_path: str | Path = OVERLAY_LOG) -> dict[str, str]:
    """rec_key -> decision, from the LAST row per rec_key (append-only rule).

    Corrections are new rows, never edits, so the last row wins. Returns an
    empty mapping for a header-only log — which is the current state, and the
    entire problem.
    """
    p = Path(log_path)
    if not p.exists():
        return {}
    try:
        df = pd.read_csv(p)
    except pd.errors.EmptyDataError:
        return {}
    if df.empty or "rec_key" not in df.columns:
        return {}
    last = df.groupby("rec_key", sort=False).tail(1)
    return dict(zip(last["rec_key"].astype(str), last["decision"].astype(str)))


def backlog(
    recs: pd.DataFrame | None = None,
    log_path: str | Path = OVERLAY_LOG,
) -> dict[str, object]:
    """Backlog summary over the whole live window. Counts only — no outcomes."""
    recs = live_window_recs() if recs is None else recs
    logged = logged_keys(log_path)
    if recs.empty:
        return {
            "n_total": 0, "n_logged": 0, "n_unlogged": 0,
            "unlogged": recs, "by_date": pd.DataFrame(), "oldest_unlogged": None,
        }
    mark = recs["rec_key"].isin(logged)
    unlogged = recs.loc[~mark].copy()
    by_date = (
        recs.assign(logged=mark)
        .groupby(recs["pick_date"].dt.strftime("%Y-%m-%d").rename("date"))
        .agg(n_recs=("rec_key", "count"), n_logged=("logged", "sum"))
        .reset_index()
    )
    by_date["n_unlogged"] = by_date["n_recs"] - by_date["n_logged"]
    return {
        "n_total": int(len(recs)),
        "n_logged": int(mark.sum()),
        "n_unlogged": int((~mark).sum()),
        "unlogged": unlogged,
        "by_date": by_date,
        "oldest_unlogged": (
            unlogged["pick_date"].min().strftime("%Y-%m-%d") if not unlogged.empty else None
        ),
    }


def command_lines(unlogged: pd.DataFrame) -> list[str]:
    """Ready-to-paste ``overlay`` command templates — one per unlogged rec.

    The operator edits the verb, size and reason; the rec_key is never
    hand-built, which is where the friction (and the typo risk) lived.
    """
    assert_outcome_blind(unlogged)
    return [
        f"overlay '{k}' EXECUTE 1 <reason>" for k in unlogged["rec_key"].astype(str)
    ]


# --- Ingest health -----------------------------------------------------------
#
# Added 2026-07-20 after com.alpha.ingest failed silently for three days
# (launchd exit 23; macOS TCC denying /bin/sh access to ~/Desktop). Nothing read
# ingest.log, so the only symptom was empty dated directories — which look
# exactly like "no recs today". That outage cost nothing only because two of the
# three days were a weekend.
#
# The pre-existing warning in overlay_today infers ingest health from REC
# staleness. That is a proxy: it cannot distinguish a dead ingest from a
# legitimately quiet day, and it only fires once a rec is already missing. These
# checks read the job's own exit status and the snapshot tree directly, so a
# failure surfaces on the day it happens.
#
# Outcome-blind: reads directory names, mtimes and an exit code. No rec contents,
# no prices, no settled results.

INGEST_LABEL = "com.alpha.ingest"
INGEST_LOG = REPO / "data" / "sealed" / "ingest.log"


def last_expected_snapshot_day(today: pd.Timestamp | None = None) -> pd.Timestamp:
    """Most recent weekday on or before ``today``.

    Weekday, not trading day: the NSE holiday calendar is not available to this
    module, so a market holiday produces one benign false warning rather than a
    silent miss. Erring toward a spurious warning is the correct direction here —
    the failure mode being guarded against is silence.
    """
    day = (today or pd.Timestamp.today()).normalize()
    while day.weekday() >= 5:  # 5 = Sat, 6 = Sun
        day -= pd.Timedelta(days=1)
    return day


def newest_populated_snapshot() -> pd.Timestamp:
    """Date of the newest NON-EMPTY snapshot directory, or NaT if none.

    Emptiness is the point: the TCC failure created correctly-named directories
    with nothing in them, so existence alone proves nothing.
    """
    if not RAW_ROOT.is_dir():
        return pd.NaT
    dates = []
    for d in RAW_ROOT.iterdir():
        if not d.is_dir() or not any(d.iterdir()):
            continue
        try:
            dates.append(pd.Timestamp(d.name))
        except ValueError:
            continue
    return max(dates) if dates else pd.NaT


def _launchd_exit_status(label: str = INGEST_LABEL) -> int | None:
    """Last exit status of a launchd job, or None if unavailable.

    Never raises: this is a diagnostic, and a diagnostic that can break the tool
    it reports on is worse than no diagnostic.
    """
    import subprocess

    try:
        out = subprocess.run(
            ["launchctl", "list"], capture_output=True, text=True, timeout=10
        ).stdout
    except (OSError, subprocess.SubprocessError):
        return None
    for line in out.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[2] == label:
            try:
                return int(parts[1])
            except ValueError:
                return None
    return None


def ingest_health(today: pd.Timestamp | None = None) -> list[str]:
    """Warnings about ingest health. Empty list means healthy."""
    warnings: list[str] = []

    status = _launchd_exit_status()
    if status is None:
        warnings.append(
            f"{INGEST_LABEL} is not loaded in launchd (or launchctl is "
            f"unavailable). The nightly snapshot may not be running at all."
        )
    elif status != 0:
        warnings.append(
            f"{INGEST_LABEL} last exited {status} (non-zero). The nightly "
            f"snapshot is FAILING. Check {INGEST_LOG.relative_to(REPO)}. "
            f"Exit 23 = rsync permission denied: grant Full Disk Access to "
            f"/bin/sh (not rsync — TCC attributes to the process launchd spawned)."
        )

    newest = newest_populated_snapshot()
    expected = last_expected_snapshot_day(today)
    if newest is pd.NaT:
        warnings.append(f"No non-empty snapshot directory under {RAW_ROOT}.")
    elif newest < expected:
        gap = (expected - newest).days
        warnings.append(
            f"Newest POPULATED snapshot is {newest:%Y-%m-%d} ({gap} day(s) "
            f"behind the last weekday, {expected:%Y-%m-%d}). Empty dated "
            f"directories look identical to a quiet day — check "
            f"{INGEST_LOG.relative_to(REPO)}. A market holiday is a benign cause."
        )
    return warnings
